"""Stores LLC certificates (and similar order documents that arrive as
files rather than being generated by an agent) in a private GCS bucket -
see app/config.py for why this is the plain google-cloud-storage client
rather than firebase-admin's storage wrapper.

The bucket has no public access at all (uniform bucket-level access +
public access prevention, set at creation). Every read goes through our
own app - see /download-certificate in app/main.py - the same pattern
already used for locally-generated PDFs at /download-pdf.
"""

from google.cloud import storage
from app.config import FIREBASE_PROJECT_ID, STORAGE_BUCKET

_client = storage.Client(project=FIREBASE_PROJECT_ID)

def _certificate_blob(order_id: str):
    bucket = _client.bucket(STORAGE_BUCKET)
    return bucket.blob(f"orders/{order_id}/certificate.pdf")

def upload_certificate(order_id: str, pdf_bytes: bytes):
    """Uploads the Certificate of Organization PDF for an order. Called
    from app/gmail_poller.py right after extracting it from the SCC
    approval email - overwrites any previous attempt, so a retry after a
    transient failure is always safe."""
    blob = _certificate_blob(order_id)
    blob.upload_from_string(pdf_bytes, content_type="application/pdf")

def fetch_certificate(order_id: str) -> bytes:
    """Raises google.cloud.exceptions.NotFound if no certificate has been
    uploaded for this order yet - callers should check the order's
    certificate_uploaded_at field first rather than relying on this to
    signal absence."""
    return _certificate_blob(order_id).download_as_bytes()

def _ein_letter_blob(order_id: str):
    bucket = _client.bucket(STORAGE_BUCKET)
    return bucket.blob(f"orders/{order_id}/ein_confirmation.pdf")

def upload_ein_letter(order_id: str, pdf_bytes: bytes):
    """Uploads the IRS CP575 EIN confirmation letter - called from
    app/main.py's run_ein_filing right after a best-effort download from
    the IRS confirmation page (see app/ein_filer.py). Best-effort on the
    scrape side means this is never guaranteed to be called; callers
    check ein_letter_uploaded_at before offering a download link."""
    blob = _ein_letter_blob(order_id)
    blob.upload_from_string(pdf_bytes, content_type="application/pdf")

def fetch_ein_letter(order_id: str) -> bytes:
    """Raises google.cloud.exceptions.NotFound if no letter has been
    uploaded for this order - callers should check ein_letter_uploaded_at
    first rather than relying on this to signal absence."""
    return _ein_letter_blob(order_id).download_as_bytes()
